In [1]:
import numpy as np

# 1. Create Arrays
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


# Day 2- NumPy Basics for Data Science 

In this notebook, I will cover the fundamentals of NumPy, a powerful Python library 
used for numerical computing and data manipulation.  
It is the foundation for most data science libraries like Pandas, SciPy, and Scikit-learn.

## Topics Covered
1. Creating NumPy Arrays
2. Special Arrays (zeros, ones, random)
3. Array Operations
4. Statistics with NumPy
5. Indexing & Slicing
6. Array Attributes (shape, size, dtype, etc.)
## Why NumPy?
- Faster than Python lists
- Supports multi-dimensional arrays
- Provides built-in mathematical functions
- Used as the base for advanced libraries (Pandas, ML libraries)



In [2]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)



2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# 2. Array of Zeros, Ones, Random Numbers
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
randoms = np.random.rand(2, 3)
print("\nArray of Zeros:\n", zeros)
print("\nArray of Ones:\n", ones)
print("\nArray of Random Numbers:\n", randoms)




Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array of Random Numbers:
 [[0.87473001 0.08247001 0.11594907]
 [0.98228216 0.36210904 0.17566084]]


In [8]:
# 3. Array Operations
arr3 = np.array([10, 20, 30, 40, 50])
print("\nOriginal Array:", arr3)

print("Array + 5:", arr3 + 5)       # Add scalar
print("Array * 2:", arr3 * 2)       # Multiply scalar
print("Array Squared:", arr3 ** 2)  # Power



Original Array: [10 20 30 40 50]
Array + 5: [15 25 35 45 55]
Array * 2: [ 20  40  60  80 100]
Array Squared: [ 100  400  900 1600 2500]


In [9]:
# 4. Statistics with NumPy
print("\nMax:", arr3.max())
print("Min:", arr3.min())
print("Mean:", arr3.mean())
print("Standard Deviation:", arr3.std())


Max: 50
Min: 10
Mean: 30.0
Standard Deviation: 14.142135623730951


In [10]:
# 5. Indexing & Slicing
print("\nFirst Element:", arr3[0])
print("Last Element:", arr3[-1])
print("Slice (1:4):", arr3[1:4])


First Element: 10
Last Element: 50
Slice (1:4): [20 30 40]
